ARTIFACT=checkers.exe

SCRIPT_DIR=$(dirname "$(realpath "$0")")

PROJECT_ROOT=$(dirname "${SCRIPT_DIR}")
DEBUG_OPTS="-g -ggdb -g3"
RELEASE_OPTS="-static-libgcc -static-libstdc++"

BUILD_PARENT_DIR=${PROJECT_ROOT}/build
DEBUG_BUILD_DIR=${BUILD_PARENT_DIR}/debug
RELEASE_BUILD_DIR=${BUILD_PARENT_DIR}/release

DEBUG_ARTIFACT=${DEBUG_BUILD_DIR}/${ARTIFACT}
RELEASE_ARTIFACT=${RELEASE_BUILD_DIR}/${ARTIFACT}

export PROJECT_ROOT
export DEBUG_OPTS
export RELEASE_OPTS
export DEBUG_ARTIFACT
export RELEASE_ARTIFACT

