SCRIPT_DIR=$(dirname "$(realpath "$0")")
PROJECT_ROOT=${SCRIPT_DIR}/../
COMPILE_OUT_PARENT=bin

COMPILE_DEBUG_OUT_DIR=${COMPILE_OUT_PARENT}/debug
DEBUG_OPTS="-ggdb -g3"

COMPILE_PROD_OUT_DIR=${COMPILE_OUT_PARENT}/prod

export PROJECT_ROOT
export COMPILE_DEBUG_OUT_DIR
export DEBUG_OPTS
export COMPILE_PROD_OUT_DIR
