CORE_PATH=/usr/bin
SCRIPT_PATH=$(pwd)
SCRIPTS_DIR=`${CORE_PATH}/dirname "${SCRIPT_PATH}"`/scripts
MINGW_HOME=/c/MinGw
GIT_HOME=/mingw64

PATH=$CORE_PATH:$SCRIPTS_DIR:$MINGW_HOME/bin:$GIT_HOME/bin

export PATH

